apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullName" . }}-training-data-pvc
  namespace: {{ template "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp2-immediate
  resources:
    requests:
      storage: 500Gi