use_inputs:
  train_type: true
  nbr_train_now: true
  year_day: false # day in the current year # TODO: try when we have several years
  year_day_dim: 3 # only used if year_day is true
  week_day: true # day in the current week
  current_time: true # time in seconds
  diff_delay: false # diff_delay and middle_diff_delay are mutually exclusive
  middle_diff_delay: false
  middle_diff_delay_bounds: [0.25, 0.75] # only used if middle_diff_delay_bounds is true
  train_nextdesserte_embedding: true
  pr_nextdesserte_embedding: true
  lignepk_embedding: true
  laplacian_embedding: true
  node2vec_embedding: true
  geographic_embedding: true
  random_embedding: true

depth: 2 # attention layers
nhead: 2 # attention heads
model_dim: 1024 #TODO were intermediate values less efficient ?
# each sillon contains the current pr of each train, as well as some infos on the previous and next prs on its itinerary
n_prev: 10 # number of prs before the snapshot time
n_foll: 40 # number of prs after the snapshot time
